# Generated by Django 3.2 on 2021-05-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_provider_name', models.CharField(max_length=500)),
                ('e_provider_password', models.CharField(max_length=500)),
                ('e_services', models.CharField(max_length=1000)),
                ('e_request_list', models.CharField(max_length=1000)),
            ],
        ),
    ]
