# Generated by Django 3.2 on 2021-05-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_email', models.CharField(max_length=500)),
                ('patient_password', models.CharField(max_length=500)),
                ('patient_name', models.CharField(max_length=500)),
                ('patient_gender', models.CharField(max_length=400)),
                ('patient_age', models.IntegerField(max_length=400)),
                ('patient_phone_number', models.IntegerField(max_length=500)),
            ],
        ),
    ]
