# Generated by Django 3.2 on 2021-05-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_phone_number',
            field=models.IntegerField(),
        ),
    ]
